### PR TITLE
added description for the new field

### PR DESCRIPTION
**Pull request by grundid**
Added description for the new field typeSelectors.

### CODE REVIEW

**Comment by deandreamatias** [comment]
Maybe need added a description that when use `typeSelectors`, `type` and `selector` don't be used by this widget. A code verification (assert) should be nice too

**Comment by grundid** [comment]
> Maybe need added a description that when use `typeSelectors`, `type` and `selector` don't be used by this widget. A code verification (assert) should be nice too

I guess an assertion will not work here since `type` and `selector` both have default values. Maybe it would be better to deprecate `type` and `selector` and put the current values into typeSelectors?

**Comment by deandreamatias** [comment]
Seems ok for me. Can add a `@deprecated` with a message in `type` and `selector` properties and add a documentation to readme with this new behaviour.
In first time, I release a minor version with this. When will has more change, I can release a major update and remove this deprecated properties

**Comment by grundid** [comment]
You want me to add something or is the current version OK?

**Comment by deandreamatias** [comment]
@grundid please add this
- a @deprecated with a message to `type` and `selector` properties 
- documentation to `readme` about this deprecated properties and how `typeSelectors` replace this deprecated properties

Thanks a lot!

**Comment by deandreamatias** [comment]
@grundid When you can, please update the main example
Thanks

**Pull request merged**
